[package]
name = "agglayer-elf-build-sample-program-host"
version = "0.5.0"
edition = "2021"
publish = false

[dependencies]
agglayer-elf-build.workspace = true

[build-dependencies]
color-eyre.workspace = true
eyre.workspace = true

agglayer-elf-build.workspace = true
